stages:
  train:
    cmd: python3 -m mlpt.models.train --config params_light_weight.yaml
    deps:
      - mlpt/models/train.py
      - params_light_weight.yaml
      - sh17-dataset
      - mlpt/utils/utils.py
    outs:
      - metrics.json
