stages:
  train:
    cmd: python -m mlpt.models.train --config configs/params_baseline.yaml
    deps:
    - requirements.txt
    - mlpt/models/train.py
    - configs/params_baseline.yaml
    - sh17-dataset
    - mlpt/utils/utils.py
    params:
    - configs/params_baseline.yaml:
      - training.epochs
      - training.batch
      - training.imgsz
      - training.mosaic
      - training.mixup
      - training.augment
      - training.fraction
    metrics:
    - metrics_train.json:
        cache: false

  tune:
    cmd: python -m mlpt.models.tune_optuna --config configs/params_baseline.yaml
    deps:
    - requirements.txt
    - mlpt/models/tune_optuna.py
    - mlpt/models/train.py
    - configs/params_baseline.yaml
    - sh17-dataset
    params:
    - configs/params_baseline.yaml:
      - tuning.n_trials
      - tuning.batch_opts
      - tuning.imgsz_opts
      - tuning.lr_min
      - tuning.lr_max
    outs:
    - models/best.pt                # <-- DVC будет кэшировать эту модель
    - logs/train.log                # <-- и этот лог
    metrics:
    - metrics.json:
        cache: false

  prune:
    cmd: python -m mlpt.models.prune --config configs/params_prune.yaml
    deps:
    - requirements.txt
    - mlpt/models/prune.py
    - mlpt/utils/utils.py
    - configs/params_prune.yaml
    - sh17-dataset
    params:
    - configs/params_prune.yaml:
      - pruning.sparsity_levels
    metrics:
    - metrics_prune.json:
        cache: false

  quantize:
    cmd: python -m mlpt.models.quantize --config configs/params_quantize.yaml
    deps:
    - requirements.txt
    - mlpt/models/quantize.py
    - configs/params_quantize.yaml
    - sh17-dataset/archive/updated_val_files.txt
    params:
    - configs/params_quantize.yaml:
      - quantization.backend
      - quantization.calib_size
      - quantization.dtype
    outs:
    - models/YOLOv11_int8.pt
    metrics:
    - metrics_quantize.json:
        cache: false

plots:
  # Baseline – бар-чарт из metrics.json
- metrics.json:
    template: simple
    x: Model          # имя столбца
    y: mAP50          # один столбец (можно список)

  # Профиль прунинга – линии mAP50 и mAP50-95
- metrics_prune.json:
    template: line
    x: sparsity
    y:
    - mAP50
    - mAP50-95
- metrics_quantize.json:
    template: bar
    x: dtype
    y:
    - mAP50
    - mAP50-95

- dvclive/plots/metrics:
    x: step
- dvclive/plots/images
- dvclive/plots/sklearn/cf.json:
    template: confusion_normalized
    x: actual
    y: predicted
    title: Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
params:
- dvclive/params.yaml
- dvclive-optuna/params.yaml
metrics:
- dvclive/metrics.json
- dvclive-optuna/metrics.json
artifacts:
  best:
    path: dvclive/artifacts/best.pt
    type: model
