stages:
  train:
    cmd: python -m mlpt.models.train --config params_baseline.yaml
    deps:
      - mlpt/models/train.py
      - params_light_weight.yaml
      - sh17-dataset
      - mlpt/utils/utils.py
    outs:
      - metrics.json
